name: Deploy Android App on AppCenter
on: 
  workflow_call:
    inputs:
      file:
        description: './build/app/outputs/apk/release/app-release.apk'
        required: true
        type: string
      name:
        description: 'Core App'
        required: true
        type: string
      group:
        description: 'C02F62W3Q05D'
        required: false
        type: string
        default: '"Collaborators"'
jobs:
  build:
    name: Build .apk file
    runs-on: self-hosted
    steps:
      - run: fvm flutter build apk --release --verbose
  Deploy:
    name: Deploy file to AppCenter
    needs: [build]
    runs-on: self-hosted
    steps:
      - name: AppCenter CLI Action
        uses: charliealbright/appcenter-cli-action@v1.0.1
        with:
          token: '13e182590e4ebeab61ea3893736d00d5da91d7c9'
          command: 'appcenter distribute release -f ${{inputs.file}} --app ${{inputs.name}} --group ${{inputs.group}}'
